---
- name: make a build dir
  file: state=directory name=/root/mysql-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/mysql-dockerized/Dockerfile

- name: put mysql.rb
  template: src=mysql.rb dest=/root/mysql-dockerized/mysql.rb

- name: put createdb.sh
  template: src=createdb.sh dest=/root/mysql-dockerized/createdb.sh mode=0755

- name: build a Docker image for MySQL
  command: docker build -t gitinsky/mysql:0.1.2 --rm /root/mysql-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/mysql:latest --rm /root/mysql-dockerized
